services:
  postgres:
    image: db-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing-sample-app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  mongo:
    image: db-mongo
    ports:
      - "27017:27017"
    networks:
      - app_network

  user-management:
    image: user-management-service
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - app_network

  catalog-management:
    image: catalog-management-service
    ports:
      - "8002:8002"
    depends_on:
      - mongo
    networks:
      - app_network

  language-management:
    image: language-management-service
    ports:
      - "8003:8003"
    depends_on:
      - postgres
    networks:
      - app_network

  ui:
    image: ui-service
    ports:
      - "8501:8501"
    depends_on:
      - user-management
      - catalog-management
      - language-management
    networks:
      - app_network

networks:
    app_network:
      driver: bridge
