services:
  postgres:
    image: diegomartinezgilabert/testing-sample-app:db-postgres-1.0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing-sample-app
    ports:
      - "5432:5432"
    networks:
      - app_network

  mongo:
    image: diegomartinezgilabert/testing-sample-app:db-mongo-1.0
    ports:
      - "27017:27017"
    networks:
      - app_network

  user-management:
    image: diegomartinezgilabert/testing-sample-app:be-user-management-service-1.0
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - app_network

  catalog-management:
    image: diegomartinezgilabert/testing-sample-app:be-catalog-management-service-1.0
    ports:
      - "8002:8002"
    depends_on:
      - mongo
    networks:
      - app_network

  language-management:
    image: diegomartinezgilabert/testing-sample-app:be-language-management-service-1.0
    ports:
      - "8003:8003"
    depends_on:
      - postgres
    networks:
      - app_network

  ui:
    image: diegomartinezgilabert/testing-sample-app:fe-ui-service-1.0
    ports:
      - "8501:8501"
    depends_on:
      - user-management
      - catalog-management
      - language-management
    networks:
      - app_network

networks:
    app_network:
      driver: bridge
