from enum import Enum

class ErrorCode(Enum):
    EMPTY_NAME = "EMPTY_NAME"
    EMPTY_DESCRIPTION = "EMPTY_DESCRIPTION"
    EMPTY_ID = "EMPTY_ID"
    EMPTY_USERNAME = "EMPTY_USERNAME"
    EMPTY_PASSWORD = "EMPTY_PASSWORD"

    NOT_FOUND = "NOT_FOUND"
    NO_LANGUAGE = "NO_LANGUAGE"
    NO_PERMISSION_ASSIGNED = "NO_PERMISSION_ASSIGNED"

    UNAUTHORIZED = "UNAUTHORIZED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    MISSING_PERMISSION = "MISSING_PERMISSION"

    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_WRONG_PASSWORD = "USER_WRONG_PASSWORD"

    ALREADY_EXIST = "ALREADY_EXIST"

    CANT_DELETE_ADMIN_USER = "CANT_DELETE_ADMIN_USER"
    CANT_DELETE_OWN_USER = "CANT_DELETE_OWN_USER"